@startuml ZXSneakers
entity Users {
 email : String(100) <PK>
 --
 name : String(20)
 password : String(100)
}

entity Admin {
 email : String(100) <PK>
 --
 password : String(100)
}

entity Products {
 Id : Int <PK>
 --
 name : String(100)
 price : Int
 stock : Int
 created_at : Datatime
 updated_at : Datetime
}

entity Product_sizes {
 id : Int (AI) <PK>
 id_product : Int <FK>
 --
 size : Int
}

entity Product_color {
 id : Int (AI) <PK>
 id_product : Int <FK>
 --
 color : String(20)
}

entity Product_images {
 id Int (AI) <PK>
 id_product : Int <FK>
 --
 name : String(100)
 format : String(4)
 data_image : BLOB
}

entity Addresses {
 id : Int (AI) <PK>
 --
 email_user : String <FK>
 --
 no_telp : String(20)
 postal_code : Int
 street : String(100)
 sub_distric : String(100)
 city : String(100)
 province : String(100)
 country : String(100)
}

entity User_profile_image {
 user_email : String <FK>
 --
 name : String(100)
 format : String(4)
 data_image : BLOB
}

object Wishlistes {
 email_user : String <FK>
 id_product : Int <FK>
}

object Buy {
 id_product : Int <FK>
 email_user : String <FK>
 --
 quantity : Int
 price_total : Int
 id : Int
 buying_time : Datetime
}

Users ||--o{ Addresses
note on link
    Have
end note
Users ||--o| User_profile_image
note on link
    Have
end note
Products ||--|{ Product_sizes
note on link
    Have
end note
Products ||--|{ Product_color
note on link
    Have
end note
Products ||--|{ Product_images
note on link
    Have
end note
Users }o-- Buy
Buy --|{ Products
Users }o-- Wishlistes
Wishlistes --|{ Products
Admin --> Products
note on link
    Add, Delete, Update
end note
@enduml